# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Str
from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from PyQt5 import QtWidgets
import pymysql
from sqlalchemy import TEXT, VARCHAR



class Ui_MainWindow(object):
    def koneksi(self):
        con = pymysql.connect(db='warung', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")
            
    def messagebox(self, title, message):
        mess =QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QMessageBox.Ok)
        mess.exec_()

    def send(self):
        NAMA = self.plainTextEdit.toPlainText()
        MAKANAN = self.plainTextEdit_2.toPlainText()
        MINUMAN = self.plainTextEdit_3.toPlainText()
        CATATAN = self.plainTextEdit_4.toPlainText()
        insert = (NAMA,MAKANAN, MINUMAN, CATATAN)
        print(insert)
        con = pymysql.connect(db='warung', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO warung(NAMA, MAKANAN, MINUMAN, CATATAN)" + \
        "VALUES"+str(insert)
        data = cur.execute(sql)
        if(data):
                self.messagebox("SUKSES", "PESANAN MU SEDANG DI PROSES")
        else:
                self.messagebox("GAGAL", "MAAF JARINGAN EROR,MOHON ULANGI KEMBALI")

    def clear(self):
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_4.setPlainText("")

    def check(self):
        NAMA = self.plainTextEdit.toPlainText()
        db = pymysql.connect(db='warung', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cursor = db.cursor()
        cursor.execute("SELECT * FROM warung WHERE NAMA='" + str(NAMA)+"'")
        data = cursor.fetchall()
        if (data):
                for tp in data:
                        self.plainTextEdit.setPlainText("" + tp[0])
                        self.plainTextEdit_2.setPlainText("" + tp[1])
                        self.plainTextEdit_3.setPlainText("" + tp[2])
                        self.plainTextEdit_4.setPlainText("" + tp[3])
                        self.messagebox("INFO","NAMA PEMESAN ADA")
        else:
                self.messagebox("INFO", "Data belum ada")

    def update(self):
        NAMA = self.plainTextEdit.toPlainText()
        MINUMAN= self.plainTextEdit_2.toPlainText()
        MAKANAN = self.plainTextEdit_3.toPlainText()
        CATATAN = self.plainTextEdit_4.toPlainText()
        con = pymysql.connect(db='warung', user='root', passwd='', host='localhost', port=3306, autocommit=True)       
        cur = con.cursor()
        sql = "UPDATE warung SET MAKANAN=%s, MINUMAN=%s, CATATAN=%s WHERE NAMA=%s"
        data = cur.execute(sql, (MAKANAN, MINUMAN, CATATAN, NAMA))

        if (data):
                self.messagebox("SUKSES", "PESANAN BERHASIL DI UPDATE")
        else:
                self.messagebox("GAGAL", sql)

    def delete(self):
        NAMA = self.plainTextEdit.toPlainText()
        con = pymysql.connect(db='warung', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "DELETE FROM warung where NAMA=%s"
        data = cur.execute(sql, (NAMA))
        if (data):
                self.messagebox("SUKSES", "Data pesanan Berhasil Di HAPUS")
        else:
                self.messagebox("GAGAL", "Data GAGAL Di HAPUS")









    def setupUi(self, MainWindow):
        self.koneksi()
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 499)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropshadowframe =QFrame(self.centralwidget)
        font = QFont()
        font.setFamily("MV Boli")
        self.dropshadowframe.setFont(font)
        self.dropshadowframe.setStyleSheet("QFrame {    \n"
"    background-color: rgb(56, 58, 89);    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropshadowframe.setFrameShape(QFrame.StyledPanel)
        self.dropshadowframe.setFrameShadow(QFrame.Raised)
        self.dropshadowframe.setObjectName("dropshadowframe")
        self.label = QLabel(self.dropshadowframe)
        self.label.setGeometry(QRect(80, 0, 321, 61))
        font = QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QCursor(Qt.CrossCursor))
        self.label.setContextMenuPolicy(Qt.CustomContextMenu)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"}")
        self.label.setObjectName("label")
        self.caramemesan = QFrame(self.dropshadowframe)
        self.caramemesan.setGeometry(QRect(10, 70, 231, 361))
        self.caramemesan.setStyleSheet("QFrame{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.caramemesan.setFrameShape(QFrame.StyledPanel)
        self.caramemesan.setFrameShadow(QFrame.Raised)
        self.caramemesan.setObjectName("caramemesan")
        self.label_2 = QLabel(self.caramemesan)
        self.label_2.setGeometry(QRect(50, 0, 131, 51))
        font =QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.formpesan_2 = QFrame(self.caramemesan)
        self.formpesan_2.setGeometry(QRect(10, 50, 211, 301))
        self.formpesan_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(254, 121, 199);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.formpesan_2.setFrameShape(QFrame.StyledPanel)
        self.formpesan_2.setFrameShadow(QFrame.Raised)
        self.formpesan_2.setObjectName("formpesan_2")
        self.textBrowser_5 = QTextBrowser(self.formpesan_2)
        self.textBrowser_5.setGeometry(QRect(10, 10, 181, 21))
        self.textBrowser_5.setStyleSheet("QTextBrowser{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QTextBrowser(self.formpesan_2)
        self.textBrowser_6.setGeometry(QRect(10, 40, 191, 91))
        self.textBrowser_6.setStyleSheet("QTextBrowser{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QTextBrowser(self.formpesan_2)
        self.textBrowser_7.setGeometry(QRect(10, 140, 191, 81))
        self.textBrowser_7.setStyleSheet("QTextBrowser{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QTextBrowser(self.formpesan_2)
        self.textBrowser_8.setGeometry(QRect(10, 230, 191, 61))
        self.textBrowser_8.setStyleSheet("QTextBrowser{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.formpesan = QFrame(self.dropshadowframe)
        self.formpesan.setGeometry(QRect(250, 70, 361, 361))
        self.formpesan.setStyleSheet("QFrame{\n"
"    background-color: rgb(254, 121, 199);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.formpesan.setFrameShape(QFrame.StyledPanel)
        self.formpesan.setFrameShadow(QFrame.Raised)
        self.formpesan.setObjectName("formpesan")
        self.label_3 = QLabel(self.formpesan)
        self.label_3.setGeometry(QRect(90, -10, 201, 71))
        font =QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setCursor(QCursor(Qt.CrossCursor))
        self.label_3.setContextMenuPolicy(Qt.CustomContextMenu)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(98, 114, 164);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_5 = QLabel(self.formpesan)
        self.label_5.setGeometry(QRect(10, 60, 51, 21))
        font = QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QLabel(self.formpesan)
        self.label_6.setGeometry(QRect(10, 100, 81, 21))
        font =QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QLabel(self.formpesan)
        self.label_7.setGeometry(QRect(10, 180, 81, 21))
        font =QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QLabel(self.formpesan)
        self.label_8.setGeometry(QRect(10, 140, 81, 21))
        font = QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"    color: rgb(254, 121, 199);\n"
"\n"
"    background-color: rgb(98, 114, 163);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.pushButton = QPushButton(self.formpesan)
        self.pushButton.setGeometry(QRect(110, 310, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.update)
        self.pushButton_2 = QPushButton(self.formpesan)
        self.pushButton_2.setGeometry(QRect(190, 310, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clear)
        self.pushButton_3 = QPushButton(self.formpesan)
        self.pushButton_3.setGeometry(QRect(270, 310, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.send)
        self.pushButton_4 = QPushButton(self.formpesan)
        self.pushButton_4.setGeometry(QRect(30, 310, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.check)
        self.plainTextEdit = QPlainTextEdit(self.formpesan)
        self.plainTextEdit.setGeometry(QRect(100, 60, 251, 31))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QPlainTextEdit(self.formpesan)
        self.plainTextEdit_2.setGeometry(QRect(100, 140, 251, 31))
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QPlainTextEdit(self.formpesan)
        self.plainTextEdit_3.setGeometry(QRect(100, 100, 251, 31))
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 =QPlainTextEdit(self.formpesan)
        self.plainTextEdit_4.setGeometry(QRect(100, 180, 251, 111))
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_5 = QPushButton(self.formpesan)
        self.pushButton_5.setGeometry(QRect(20, 260, 75, 31))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color: rgb(255, 0, 0);}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.delete)
        self.DESIGN = QFrame(self.dropshadowframe)
        self.DESIGN.setGeometry(QRect(20, 20, 51, 31))
        self.DESIGN.setStyleSheet("QFrame{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(56, 58, 89);\n"
"    border-color: rgb(56, 58, 89);\n"
"    border-radius: 3px\n"
"\n"
"}")
        self.DESIGN.setFrameShape(QFrame.StyledPanel)
        self.DESIGN.setFrameShadow(QFrame.Raised)
        self.DESIGN.setObjectName("DESIGN")
        self.verticalLayout.addWidget(self.dropshadowframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar =QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar =QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate =QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "WARUNG BU IS "))
        self.label_2.setText(_translate("MainWindow", "CARA MEMESAN "))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. MASUKAN NAMA KAMU</p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. MASUKAN MENU MAKANAN KE</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    FORM MAKANAN BESERTA JUMLAH  <br />    CONTOH :</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    NASI GORENG (2)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    RAMES (1)</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. MASUKAN MENU MINUMAN KE</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    FORM MINUMAN BESERTA JUMLAH  <br />    CONTOH :</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    NASI GORENG (2)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    RAMES (1)</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. BUAT CATATAN </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    MISAL : </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     NASI GORENGNYA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    JANGAN PEDAS YA</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "FORM PESANAN"))
        self.label_5.setText(_translate("MainWindow", "NAMA"))
        self.label_6.setText(_translate("MainWindow", "MAKANAN"))
        self.label_7.setText(_translate("MainWindow", "CATATAN"))
        self.label_8.setText(_translate("MainWindow", "MINUMAN"))
        self.pushButton.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_3.setText(_translate("MainWindow", "SEND"))
        self.pushButton_4.setText(_translate("MainWindow", "CHECK"))
        self.pushButton_5.setText(_translate("MainWindow", "DELETE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
